import React, {Component} from 'react';
import '../styles/testText.scss';

export default class TestTextPage extends Component {
    render() {
        return (
            <div>
                <img src={require('../asserts/bg.jpg')}/>
                <div>start</div>
                <div>哈哈哈</div>
                <div>哈哈哈</div>
                <div>哈哈哈</div>
                <div>哈哈哈</div>
                <div>哈哈哈</div>
                <div>哈哈哈</div>
                <div>哈哈哈</div>
                <div>哈哈哈</div>
                <div>哈哈哈</div>
                <div>哈哈哈</div>
                <div>哈哈哈</div>
                <div>哈哈哈</div>
                <div>哈哈哈</div>
                <div>哈哈哈</div>
                <div>哈哈哈</div>
                <div>哈哈哈</div>
                <div>哈哈哈</div>
                <div>哈哈哈</div>
                <div>哈哈哈</div>
                <div>哈哈哈</div>
                <div>哈哈哈</div>
                <div>哈哈哈</div>
                <div>哈哈哈</div>
                <div>哈哈哈</div>
                <div>哈哈哈</div>
                <div>哈哈哈</div>
                <div>哈哈哈</div>
                <div>哈哈哈</div>
                <div>哈哈哈</div>
                <div>哈哈哈</div>
                <div>哈哈哈</div>
                <div>哈哈哈</div>
                <div>哈哈哈</div>
                <div>哈哈哈</div>
                <div>哈哈哈</div>
                <div>哈哈哈</div>
                <div>哈哈哈</div>
                <div>哈哈哈</div>
                <div>哈哈哈</div>
                <div>哈哈哈</div>
                <div>哈哈哈</div>
                <div>哈哈哈</div>
                <div>哈哈哈</div>
                <div>哈哈哈</div>
                <div>哈哈哈</div>
                <div>哈哈哈</div>
                <div>哈哈哈</div>
                <div>哈哈哈</div>
                <div>哈哈哈</div>
                <div>哈哈哈</div>
                <div>哈哈哈</div>
                <div>哈哈哈</div>
                <div>哈哈哈</div>
                <div>哈哈哈</div>
                <div>哈哈哈</div>
                <div>哈哈哈</div>
                <div>哈哈哈</div>
                <div>哈哈哈</div>
                <div>哈哈哈</div>
                <div>哈哈哈</div>
                <div>哈哈哈</div>
                <div>哈哈哈</div>
                <div>哈哈哈</div>
                <div>哈哈哈</div>
                <div>哈哈哈</div>
                <div>哈哈哈</div>
                <div>哈哈哈</div>
                <div>哈哈哈</div>
                <div>哈哈哈</div>
                <div>哈哈哈</div>
                <div>哈哈哈</div>
                <div>哈哈哈</div>
                <div>哈哈哈</div>
                <div>哈哈哈</div>
                <div>哈哈哈</div>
                <div>哈哈哈</div>
                <div>哈哈哈</div>
                <div>哈哈哈</div>
                <div>哈哈哈</div>
                <div>哈哈哈</div>
                <div>哈哈哈</div>
                <div>哈哈哈</div>
                <div>哈哈哈</div>
                <div>哈哈哈</div>
                <div>哈哈哈</div>
                <div>哈哈哈</div>
                <div>哈哈哈</div>
                <div>哈哈哈</div>
                <div>哈哈哈</div>
                <div>哈哈哈</div>
                <div>哈哈哈</div>
                <div>哈哈哈</div>
                <div>哈哈哈</div>
                <div>哈哈哈</div>
                <div>哈哈哈</div>
                <div>哈哈哈</div>
                <div>哈哈哈</div>
                <div>哈哈哈</div>
                <div>哈哈哈</div>
                <div>哈哈哈</div>
                <div>哈哈哈</div>
                <div>哈哈哈</div>
                <div>哈哈哈</div>
                <div>哈哈哈</div>
                <div>哈哈哈</div>
                <div>哈哈哈</div>
                <div>哈哈哈</div>
                <div>哈哈哈</div>
                <div>哈哈哈</div>
                <div>哈哈哈</div>
                <div>哈哈哈</div>
                <div>哈哈哈</div>
                <div>end</div>
            </div>
        );
    }
}